import type { Vendor, LeaderboardUser } from '@/lib/types';

export const vendors: Vendor[] = [
  {
    id: '1',
    name: 'Eco-Catering Co.',
    description: 'Delicious, locally-sourced organic catering for events of all sizes. We prioritize zero-waste and compost all food scraps.',
    services: ['Catering', 'Zero-Waste'],
    certifications: ['Certified B-Corp', 'Green Seal'],
    imageUrl: 'https://picsum.photos/seed/101/600/400',
    imageHint: 'food catering',
    sustainabilityScore: 95,
  },
  {
    id: '2',
    name: 'Green Stage Productions',
    description: 'Sustainable event staging, lighting, and sound powered by renewable energy. We use LED lighting and recycled materials.',
    services: ['Staging', 'AV', 'Lighting'],
    certifications: ['ISO 20121'],
    imageUrl: 'https://picsum.photos/seed/102/600/400',
    imageHint: 'event stage',
    sustainabilityScore: 88,
  },
  {
    id: '3',
    name: 'ReBloom Floral & Decor',
    description: 'Beautiful, sustainable floral arrangements and event decor. We source from local farms and use reusable or compostable materials.',
    services: ['Decorations', 'Floral'],
    certifications: ['Fair Trade'],
    imageUrl: 'https://picsum.photos/seed/103/600/400',
    imageHint: 'event decorations',
    sustainabilityScore: 92,
  },
  {
    id: '4',
    name: 'GoGreen Transport',
    description: 'Eco-friendly transportation solutions for your attendees, including electric shuttles and carbon-offsetting programs.',
    services: ['Transportation'],
    certifications: [],
    imageUrl: 'https://picsum.photos/seed/104/600/400',
    imageHint: 'electric bus',
    sustainabilityScore: 85,
  },
  {
    id: '5',
    name: 'Compost-a-Plate',
    description: 'Provider of 100% compostable plates, cutlery, and cups made from plant-based materials.',
    services: ['Serviceware'],
    certifications: ['BPI Certified'],
    imageUrl: 'https://picsum.photos/seed/105/600/400',
    imageHint: 'bamboo cutlery',
    sustainabilityScore: 98,
  },
  {
    id: '6',
    name: 'SolarSound Systems',
    description: 'High-quality sound systems for events, fully powered by portable solar arrays. Crystal clear sound with zero emissions.',
    services: ['AV', 'Power'],
    certifications: [],
    imageUrl: 'https://picsum.photos/seed/106/600/400',
    imageHint: 'sound system',
    sustainabilityScore: 90,
  },
];

export const leaderboard: LeaderboardUser[] = [
  { rank: 1, name: 'Samantha Bee', points: 1250, avatarUrl: 'https://picsum.photos/seed/user1/100/100', avatarHint: 'woman portrait' },
  { rank: 2, name: 'David Chen', points: 1180, avatarUrl: 'https://picsum.photos/seed/user2/100/100', avatarHint: 'man portrait' },
  { rank: 3, name: 'Maria Garcia', points: 1125, avatarUrl: 'https://picsum.photos/seed/user3/100/100', avatarHint: 'woman smiling' },
  { rank: 4, name: 'Alex Johnson', points: 1050, avatarUrl: 'https://picsum.photos/seed/user4/100/100', avatarHint: 'person glasses' },
  { rank: 5, name: 'Fatima Ahmed', points: 980, avatarUrl: 'https://picsum.photos/seed/user5/100/100', avatarHint: 'woman headscarf' },
  { rank: 6, name: 'Ben Carter', points: 955, avatarUrl: 'https://picsum.photos/seed/user6/100/100', avatarHint: 'man smiling' },
  { rank: 7, name: 'Olivia White', points: 920, avatarUrl: 'https://picsum.photos/seed/user7/100/100', avatarHint: 'woman blonde' },
  { rank: 8, name: 'Leo Martinez', points: 890, avatarUrl: 'https://picsum.photos/seed/user8/100/100', avatarHint: 'man beard' },
];
